"""summary/prompt.py — System and user prompt builders.

Exact port of apps/worker/src/summary/prompt.ts.
The system prompt text MUST remain identical so summaries generated by the
local engine are editorially equivalent to those from the Worker.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class SummaryItem:
    item_id: str
    title_he: str
    source_id: str
    published_at: str | None = None


def build_system_prompt(risk_level: str) -> str:
    """Build the system prompt with editorial rules and mandatory format."""
    high_risk_note = (
        '\n- ОБЯЗАТЕЛЬНО: добавь "по данным источников" в раздел "Что произошло".'
        if risk_level == "high"
        else ""
    )

    return (
        "Ты профессиональный редактор русскоязычных новостей, пересказывающий израильские новости с иврита.\n"
        "\n"
        "Создай пересказ на русском, используя СТРОГО следующую структуру (все 5 разделов обязательны):\n"
        "\n"
        "Заголовок: <одна фактическая строка>\n"
        "Что произошло: <1–2 предложения>\n"
        "Почему важно: <1 предложение>\n"
        "Что дальше: <1 предложение или \"Ожидается обновление.\">\n"
        "Источники: <названия источников через запятую>\n"
        "\n"
        "Правила:\n"
        "- Язык: только русский (кроме названий источников)\n"
        "- Длина тела (без строки \"Источники\"): 400–700 символов\n"
        "- Сохраняй все числа, проценты и суммы точно\n"
        "- Используй точно: ЦАХАЛ, ШАБАК, Кнессет, Тель-Авив, Иерусалим, Хайфа\n"
        "- Тон: нейтральный и фактологичный, без эмоций\n"
        f"- Запрещённые слова: ужас, кошмар, шок, сенсация, скандал{high_risk_note}"
    )


def build_user_message(items: list[SummaryItem]) -> str:
    """Build the user message listing Hebrew news items."""
    lines = [f"{i + 1}. [{it.source_id}] {it.title_he}" for i, it in enumerate(items)]
    return "Новостные заголовки на иврите:\n" + "\n".join(lines)
